
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 24 02:35:18 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 7;
  public static final int ELSE = 13;
  public static final int NOTEQ = 19;
  public static final int INT = 8;
  public static final int LEFTPAR = 3;
  public static final int GREATER = 20;
  public static final int INTCONST = 23;
  public static final int RIGHTPAR = 4;
  public static final int IF = 11;
  public static final int COLON = 14;
  public static final int ID = 22;
  public static final int EOF = 0;
  public static final int REALCONST = 24;
  public static final int MAIN = 2;
  public static final int GREATEREQ = 21;
  public static final int ELIF = 12;
  public static final int error = 1;
  public static final int EQ = 18;
  public static final int LESSEQ = 17;
  public static final int ASSIGN = 15;
  public static final int BOOL = 10;
  public static final int REAL = 9;
  public static final int BOOLCONST = 25;
  public static final int LESS = 16;
  public static final int RIGHTCURLY = 6;
  public static final int LEFTCURLY = 5;
}

