
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 01 19:35:25 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 8;
  public static final int ELSE = 14;
  public static final int NOTEQ = 21;
  public static final int INT = 9;
  public static final int LEFTPAR = 3;
  public static final int GREATER = 22;
  public static final int RIGHTPAR = 4;
  public static final int IF = 12;
  public static final int COLON = 16;
  public static final int ID = 7;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int GREATEREQ = 23;
  public static final int ELIF = 13;
  public static final int CONST = 15;
  public static final int error = 1;
  public static final int EQ = 20;
  public static final int LESSEQ = 19;
  public static final int ASSIGN = 17;
  public static final int BOOL = 11;
  public static final int REAL = 10;
  public static final int LESS = 18;
  public static final int RIGHTCURLY = 6;
  public static final int LEFTCURLY = 5;
}

